### ISSUE TITLE
Eliminate need to insert into SchemaVersion table at start of "full" migration script

### ISSUE THREAD

**Issue by johnstairs** [microsoft/healthcare-shared-components#113]
We should be able to eliminate this from the start of every 6.sql, 7.sql, etc file:

```SQL
/*************************************************************
    Schema Version
**************************************************************/

INSERT INTO dbo.SchemaVersion
VALUES
    (6, 'started')

GO
```

Instead, we could insert the row before calling the script, like we do for .diff.sql scripts.

**Comment by rbans96** [comment]
Created #[AB76682](https://microsofthealth.visualstudio.com/Health/_boards/board/t/Resolute/Stories/?workitem=76682).
