### ISSUE TITLE
SqlServer initilization doesn't push schema on newly created database.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/healthcare-shared-components#196]
**Describe the bug**
I had to specify sqlSchemaAutomaticUpdatesEnabled to populate database with scripts on new database. Overwise database is empty. 
**To Reproduce**
1. Set database name which doesn't exist.
2. Set `AllowDatabaseCreation` to true.
3.  Run `SchemaInitializer` - you will have database, but it would be empty.

**Expected behavior**
I expect to have all tables and SP in newly created database. 

**Actual behavior**
Empty database.

**Workaround**
I have to manually specify sqlSchemaAutomaticUpdatesEnabled to true to populate DB.

**Comment by Ivanidzo4ka** [comment]
@rbans96 is this expected behaviour?

**Comment by rbans96** [comment]
yes, this is expected behavior. Since we want to control schema initialization using the flag sqlSchemaAutomaticUpdatesEnabled.
If the flag sets to false, empty database is created by the application and then we need to run the schema migration tool to initialize the schema.

**Comment by Ivanidzo4ka** [comment]
But what's the user case for that? Is it for case where we want to roll back to old version of schema? 
I just find it frustrating to run tool as second step. Does it mean if customer using our azure templates and set up to use tool to do migration they get service which can't work until they use tool?

**Comment by rbans96** [comment]
Sorry for the inconvenience. But the overall idea is, we want to separate out the schema admin permissions from the fhir application. And only DB Admin should have privileges to run the tool.
For ex- In health-paas, RP Worker would be given schema admin privileges to initialize the schema and fhir application would just start up and read/write to the db tables based on customer interactions with our apis.

If you have further questions, I am available for quick call/chat to discuss more.
