### ISSUE TITLE
We should avoid creating `HttpClient`

### ISSUE THREAD

**Issue by jovinson-ms** [microsoft/healthcare-shared-components#317]
We should consider injecting `IHttpClientFactory` instead: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

https://github.com/microsoft/healthcare-shared-components/blob/1e0dc8532113a5f7fdd0692c922e91b8273c240e/src/Microsoft.Health.SqlServer/Features/Schema/Manager/SchemaClient.cs#L25

**Comment by wbalbo** [comment]
Please assign this to me. Probably will not need a unit test for this, since the constructor is not called anywhere in the code, is just used to instantiate the HttpClient class.

Thanks.

**Comment by jovinson-ms** [comment]
Great! You can remove the `IDisposable` implementation once we we're using the factory, and the existing tests should continue to pass.

**Comment by wbalbo** [comment]
Yes, I had a problem only with tests related to the SQL Server database, but is not because I changed the implementation, is only because I didn't create a SQL connection.
