### ISSUE TITLE
Refactor `SchemaManager`

### ISSUE THREAD

**Issue by jovinson-ms** [microsoft/healthcare-shared-components#319]
The `SchemaManager` tool under `\tools` could be improved in a few ways:
- The namespace should begin with `Microsoft.Health`, not `SchemaManager`
- There are `SchemaManager` and `SchemaManager.Core` projects that aren't used for different purposes
- Dependencies are manually registered in [Program.cs](https://github.com/microsoft/healthcare-shared-components/blob/72baa0809d2282e9d35eebe70bf74ff4b7b698be/tools/SchemaManager/Program.cs#L47) rather than using the registration methods in [Microsoft.Health.SqlServer.Registration](https://github.com/microsoft/healthcare-shared-components/blob/72baa0809d2282e9d35eebe70bf74ff4b7b698be/src/Microsoft.Health.SqlServer/Registration/SqlServerBaseRegistrationExtensions.cs#L24).
- `SchemaManager` dependency registration isn't tested

**Comment by rahulbhatt1899** [comment]
Hey, I m fairly a beginner in .NET, and C# has only been 3 - 4 months, except for the testing part I think I can contribute to this issue.

**Comment by jovinson-ms** [comment]
Great! Why don't you take a look at the code, and then bullet point the changes you plan to make and I'll be happy to provide feedback.

**Comment by rahulbhatt1899** [comment]
Sure

**Comment by jovinson-ms** [comment]
Looks good  - I would add a fourth step to run an integration test on the tool to ensure that when we run a command, the behavior is correct.

**Comment by rahulbhatt1899** [comment]
@jovinson-ms I m sorry, I have no experience in testing yet, if you could help me with it, I'll do it.

**Comment by wbalbo** [comment]
> @jovinson-ms I m sorry, I have no experience in testing yet, if you could help me with it, I'll do it.

Hey, you can see some examples here, in this project:

https://github.com/microsoft/healthcare-shared-components/blob/master/test/Microsoft.Health.SqlServer.Tests.Integration/Features/Schema/SchemaInitializerTests.cs

A very good tutorial about xUnit tests here: https://www.youtube.com/watch?v=ub3P8c87cwk

Is not hard, I learned recently, just follow the examples, create a test project first and learn a bit, then make your changes in your branch, push here and let us know.

PS: I'm not affiliated with this project, just another contributor trying to help, good luck.

**Comment by jovinson-ms** [comment]
Should have closed this earlier - we had to pause this while some urgent changes went in, and there's now an effort underway to refactor. Thanks all for the input!
